/*
 *
 * Task code generated by SAS Studio 3.5 
 *
 * Generated on '9/13/16, 1:54 PM' 
 * Generated by 'jimbox' 
 * Generated on server 'L7A368.NA.SAS.COM' 
 * Generated on SAS platform 'X64_7PRO WIN' 
 * Generated on SAS version '9.04.01M3P06242015' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' 
 * Generated on web client 'http://localhost:49528/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257BB672A86B-A04E-414E-866D-3C124C3FDA5B%257D' 
 *
 */

/* Option group 5 (GRAPH SIZE) parameters. */
/*--Set output size--*/
ods graphics / reset imagemap;

/*--SGPLOT proc statement--*/
proc sgplot data=RAWDATA.VS 
         (where=(ORNTEMPU="C"));
	/*--Histogram settings--*/
	histogram ORNTEMP /;

	/*--Vertical or Response Axis--*/
	yaxis grid;
run;

ods graphics / reset;